# Generated by Django 4.2.23 on 2025-08-17 03:27

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Anbi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("beleidsplan", models.FileField(upload_to="anbi")),
                ("beschrijving", tinymce.models.HTMLField()),
                ("jaar", models.IntegerField(help_text="Jaar van het beleidsplan")),
            ],
            options={
                "verbose_name": "ANBI",
                "verbose_name_plural": "ANBI documenten",
                "ordering": ["-jaar"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("file", models.FileField(upload_to="documents")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Over",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("titel", models.CharField(max_length=128)),
                ("info", tinymce.models.HTMLField()),
            ],
            options={
                "verbose_name": "Over ons",
                "verbose_name_plural": "Over ons",
            },
        ),
        migrations.CreateModel(
            name="Overeenkomst",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("naam", models.CharField(max_length=128)),
                ("beschrijving", tinymce.models.HTMLField()),
                (
                    "document",
                    models.FileField(blank=True, null=True, upload_to="overeenkomsten"),
                ),
            ],
            options={
                "verbose_name": "Overeenkomst",
                "verbose_name_plural": "Overeenkomsten",
                "ordering": ["naam"],
            },
        ),
        migrations.CreateModel(
            name="Sponsor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("naam", models.CharField(max_length=128)),
                ("link", models.URLField(blank=True, null=True)),
                ("beschrijving", tinymce.models.HTMLField()),
                (
                    "image",
                    models.ImageField(default="default.jpg", upload_to="sponsor"),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0, help_text="Hogere waarde = hogere prioriteit"
                    ),
                ),
            ],
            options={
                "verbose_name": "Sponsor",
                "verbose_name_plural": "Sponsors",
                "ordering": ["-priority"],
            },
        ),
    ]
