# Generated by Django 4.2.23 on 2025-08-17 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stichting", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anbi",
            name="beleidsplan",
            field=models.FileField(blank=True, upload_to="anbi"),
        ),
    ]
