# Generated by Django 4.2.23 on 2025-08-17 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stichting", "0002_alter_anbi_beleidsplan"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Over",
        ),
    ]
