# Generated by Django 4.2.23 on 2025-08-17 03:27

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("knack", "0007_alter_docent_options_alter_instrument_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Groep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("naam", models.CharField(max_length=128)),
                ("beschrijving", tinymce.models.HTMLField()),
                ("link", models.URLField(blank=True, null=True)),
                ("image", models.ImageField(default="default.jpg", upload_to="groep")),
            ],
            options={
                "verbose_name": "Groep",
                "verbose_name_plural": "Groepen",
                "ordering": ["naam"],
            },
        ),
        migrations.CreateModel(
            name="Workshop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("naam", models.CharField(max_length=128)),
                ("beschrijving", tinymce.models.HTMLField()),
                ("prijs", models.FloatField()),
                ("duur", models.CharField(max_length=128)),
                ("link", models.URLField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(default="default.jpg", upload_to="workshop"),
                ),
                (
                    "instrumenten",
                    models.ManyToManyField(blank=True, to="knack.instrument"),
                ),
            ],
            options={
                "verbose_name": "Workshop",
                "verbose_name_plural": "Workshops",
                "ordering": ["naam"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("naam", models.CharField(max_length=128)),
                ("beschrijving", tinymce.models.HTMLField()),
                ("prijs", models.FloatField()),
                ("duur", models.CharField(max_length=128)),
                ("link", models.URLField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(default="default.jpg", upload_to="project"),
                ),
                ("start", models.DateField()),
                ("end", models.DateField()),
                (
                    "instrumenten",
                    models.ManyToManyField(blank=True, to="knack.instrument"),
                ),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projecten",
                "ordering": ["start", "naam"],
            },
        ),
        migrations.CreateModel(
            name="Cursus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("naam", models.CharField(max_length=128)),
                ("beschrijving", tinymce.models.HTMLField()),
                ("prijs", models.FloatField()),
                ("duur", models.CharField(max_length=128)),
                ("link", models.URLField(blank=True, null=True)),
                ("image", models.ImageField(default="default.jpg", upload_to="cursus")),
                (
                    "instrumenten",
                    models.ManyToManyField(blank=True, to="knack.instrument"),
                ),
            ],
            options={
                "verbose_name": "Cursus",
                "verbose_name_plural": "Cursussen",
                "ordering": ["naam"],
            },
        ),
    ]
