# Generated by Django 4.2.7 on 2025-06-19 16:04

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("knack", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Anbi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("beleidsplan", models.FileField(upload_to="anbi")),
                ("beschrijving", tinymce.models.HTMLField()),
                ("jaar", models.IntegerField(help_text="Jaar van het beleidsplan")),
            ],
            options={
                "verbose_name": "ANBI",
                "verbose_name_plural": "ANBI documenten",
                "ordering": ["-jaar"],
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("organisatie", models.CharField(max_length=128)),
                ("adres", models.CharField(max_length=128)),
                ("postcode", models.CharField(max_length=6)),
                ("plaats", models.CharField(max_length=128)),
                ("email", models.EmailField(max_length=128)),
                ("telefoon", models.CharField(max_length=128)),
                ("kvk_nr", models.CharField(blank=True, max_length=128, null=True)),
                ("btw_nr", models.CharField(blank=True, max_length=128, null=True)),
                ("website", models.URLField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Contact",
                "verbose_name_plural": "Contactgegevens",
            },
        ),
        migrations.CreateModel(
            name="Groep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("naam", models.CharField(max_length=128)),
                ("beschrijving", tinymce.models.HTMLField()),
                ("link", models.URLField(blank=True, null=True)),
                ("image", models.ImageField(default="default.jpg", upload_to="groep")),
            ],
            options={
                "verbose_name": "Groep",
                "verbose_name_plural": "Groepen",
                "ordering": ["naam"],
            },
        ),
        migrations.CreateModel(
            name="Header",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("titel", models.CharField(max_length=128)),
                ("info", tinymce.models.HTMLField()),
                (
                    "background_image",
                    models.ImageField(blank=True, null=True, upload_to="headers"),
                ),
            ],
            options={
                "verbose_name": "Header",
                "verbose_name_plural": "Headers",
                "ordering": ["titel"],
            },
        ),
        migrations.CreateModel(
            name="Over",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("titel", models.CharField(max_length=128)),
                ("info", tinymce.models.HTMLField()),
            ],
            options={
                "verbose_name": "Over ons",
                "verbose_name_plural": "Over ons",
            },
        ),
        migrations.CreateModel(
            name="Overeenkomst",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("naam", models.CharField(max_length=128)),
                ("beschrijving", tinymce.models.HTMLField()),
                (
                    "document",
                    models.FileField(blank=True, null=True, upload_to="overeenkomsten"),
                ),
            ],
            options={
                "verbose_name": "Overeenkomst",
                "verbose_name_plural": "Overeenkomsten",
                "ordering": ["naam"],
            },
        ),
        migrations.CreateModel(
            name="PromoFoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("naam", models.CharField(max_length=128)),
                ("image", models.ImageField(default="default.jpg", upload_to="promo")),
                ("alt_text", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "verbose_name": "Promo foto",
                "verbose_name_plural": "Promo foto's",
                "ordering": ["naam"],
            },
        ),
        migrations.CreateModel(
            name="Sponsor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("naam", models.CharField(max_length=128)),
                ("link", models.URLField(blank=True, null=True)),
                ("beschrijving", tinymce.models.HTMLField()),
                (
                    "image",
                    models.ImageField(default="default.jpg", upload_to="sponsor"),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0, help_text="Hogere waarde = hogere prioriteit"
                    ),
                ),
            ],
            options={
                "verbose_name": "Sponsor",
                "verbose_name_plural": "Sponsors",
                "ordering": ["-priority", "naam"],
            },
        ),
        migrations.CreateModel(
            name="Workshop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("naam", models.CharField(max_length=128)),
                ("beschrijving", tinymce.models.HTMLField()),
                ("prijs", models.FloatField()),
                ("duur", models.CharField(max_length=128)),
                ("link", models.URLField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(default="default.jpg", upload_to="workshop"),
                ),
                (
                    "instrumenten",
                    models.ManyToManyField(blank=True, to="knack.instrument"),
                ),
            ],
            options={
                "verbose_name": "Workshop",
                "verbose_name_plural": "Workshops",
                "ordering": ["naam"],
            },
        ),
        migrations.CreateModel(
            name="Vacature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("functie", models.CharField(max_length=128)),
                ("beschrijving", tinymce.models.HTMLField()),
                ("deadline", models.DateField(blank=True, null=True)),
                ("salaris", models.CharField(blank=True, max_length=128)),
                (
                    "instrumenten",
                    models.ManyToManyField(blank=True, to="knack.instrument"),
                ),
            ],
            options={
                "verbose_name": "Vacature",
                "verbose_name_plural": "Vacatures",
                "ordering": ["functie"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("naam", models.CharField(max_length=128)),
                ("beschrijving", tinymce.models.HTMLField()),
                ("prijs", models.FloatField()),
                ("duur", models.CharField(max_length=128)),
                ("link", models.URLField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(default="default.jpg", upload_to="project"),
                ),
                ("start", models.DateField()),
                ("end", models.DateField()),
                (
                    "instrumenten",
                    models.ManyToManyField(blank=True, to="knack.instrument"),
                ),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projecten",
                "ordering": ["start", "naam"],
            },
        ),
        migrations.CreateModel(
            name="Cursus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("naam", models.CharField(max_length=128)),
                ("beschrijving", tinymce.models.HTMLField()),
                ("prijs", models.FloatField()),
                ("duur", models.CharField(max_length=128)),
                ("link", models.URLField(blank=True, null=True)),
                ("image", models.ImageField(default="default.jpg", upload_to="cursus")),
                (
                    "instrumenten",
                    models.ManyToManyField(blank=True, to="knack.instrument"),
                ),
            ],
            options={
                "verbose_name": "Cursus",
                "verbose_name_plural": "Cursussen",
                "ordering": ["naam"],
            },
        ),
    ]
