# Generated by Django 4.2.7 on 2025-06-30 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("muziekschool", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cursus",
            name="image",
            field=models.ImageField(default="default.png", upload_to="cursus"),
        ),
        migrations.AlterField(
            model_name="groep",
            name="image",
            field=models.ImageField(default="default.png", upload_to="groep"),
        ),
        migrations.AlterField(
            model_name="project",
            name="end",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.ImageField(default="default.png", upload_to="project"),
        ),
        migrations.AlterField(
            model_name="project",
            name="start",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="promofoto",
            name="image",
            field=models.ImageField(default="default.png", upload_to="promo"),
        ),
        migrations.AlterField(
            model_name="sponsor",
            name="image",
            field=models.ImageField(default="default.png", upload_to="sponsor"),
        ),
        migrations.AlterField(
            model_name="workshop",
            name="image",
            field=models.ImageField(default="default.png", upload_to="workshop"),
        ),
    ]
