# Generated by Django 4.2.7 on 2025-06-30 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("muziekschool", "0002_alter_cursus_image_alter_groep_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="end",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="project",
            name="start",
            field=models.DateField(),
        ),
    ]
