# Generated by Django 4.2.7 on 2025-06-30 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("muziekschool", "0003_alter_project_end_alter_project_start"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="project",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="project",
            name="updated_at",
        ),
    ]
