# Generated by Django 4.2.7 on 2025-07-29 14:21

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        (
            "muziekschool",
            "0004_remove_project_created_at_remove_project_is_active_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("titel", models.CharField(max_length=128)),
                ("info", tinymce.models.HTMLField()),
                (
                    "background_image",
                    models.ImageField(blank=True, null=True, upload_to="banners"),
                ),
            ],
            options={
                "verbose_name": "Banner",
                "verbose_name_plural": "Banners",
                "ordering": ["titel"],
            },
        ),
    ]
