# Generated by Django 4.2.7 on 2025-07-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("muziekschool", "0005_banner"),
    ]

    operations = [
        migrations.AddField(
            model_name="banner",
            name="banner_type",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
