# Generated by Django 4.2.23 on 2025-08-12 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("muziekschool", "0006_banner_banner_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="documents")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name="cursus",
            name="image",
            field=models.ImageField(default="default.jpg", upload_to="cursus"),
        ),
        migrations.AlterField(
            model_name="groep",
            name="image",
            field=models.ImageField(default="default.jpg", upload_to="groep"),
        ),
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.ImageField(default="default.jpg", upload_to="project"),
        ),
        migrations.AlterField(
            model_name="promofoto",
            name="image",
            field=models.ImageField(default="default.jpg", upload_to="promo"),
        ),
        migrations.AlterField(
            model_name="sponsor",
            name="image",
            field=models.ImageField(default="default.jpg", upload_to="sponsor"),
        ),
        migrations.AlterField(
            model_name="workshop",
            name="image",
            field=models.ImageField(default="default.jpg", upload_to="workshop"),
        ),
    ]
