# Generated by Django 4.2.23 on 2025-08-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("muziekschool", "0007_document_alter_cursus_image_alter_groep_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="title",
            field=models.CharField(default="doc1", max_length=200),
            preserve_default=False,
        ),
    ]
