# Generated by Django 4.2.23 on 2025-08-16 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("muziekschool", "0008_document_title"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sponsor",
            options={
                "ordering": ["priority", "naam"],
                "verbose_name": "Sponsor",
                "verbose_name_plural": "Sponsors",
            },
        ),
    ]
