# Generated by Django 4.2.23 on 2025-08-16 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("muziekschool", "0010_alter_sponsor_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sponsor",
            options={
                "ordering": ["-priority"],
                "verbose_name": "Sponsor",
                "verbose_name_plural": "Sponsors",
            },
        ),
    ]
