# Generated by Django 4.2.23 on 2025-08-17 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("muziekschool", "0011_alter_sponsor_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Anbi",
        ),
        migrations.RemoveField(
            model_name="cursus",
            name="instrumenten",
        ),
        migrations.DeleteModel(
            name="Document",
        ),
        migrations.DeleteModel(
            name="Groep",
        ),
        migrations.DeleteModel(
            name="Over",
        ),
        migrations.DeleteModel(
            name="Overeenkomst",
        ),
        migrations.RemoveField(
            model_name="project",
            name="instrumenten",
        ),
        migrations.DeleteModel(
            name="Sponsor",
        ),
        migrations.RemoveField(
            model_name="workshop",
            name="instrumenten",
        ),
        migrations.DeleteModel(
            name="Cursus",
        ),
        migrations.DeleteModel(
            name="Project",
        ),
        migrations.DeleteModel(
            name="Workshop",
        ),
    ]
