# Generated by Django 4.2.23 on 2025-08-17 03:56

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("muziekschool", "0012_delete_anbi_remove_cursus_instrumenten_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Over",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("titel", models.CharField(max_length=128)),
                ("info", tinymce.models.HTMLField()),
            ],
            options={
                "verbose_name": "Over ons",
                "verbose_name_plural": "Over ons",
            },
        ),
    ]
