# Generated by Django 4.2.23 on 2025-08-19 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("muziekschool", "0013_over"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PromoFoto",
        ),
    ]
