# Generated by Django 4.2.23 on 2025-08-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("muziekschool", "0014_delete_promofoto"),
    ]

    operations = [
        migrations.AddField(
            model_name="banner",
            name="priority",
            field=models.IntegerField(default=0, help_text="Volgorde homepage"),
        ),
    ]
