# Generated by Django 4.2.23 on 2025-08-29 14:30

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("muziekschool", "0015_banner_priority"),
    ]

    operations = [
        migrations.CreateModel(
            name="Voorwaarde",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("titel", models.CharField(max_length=128)),
                ("info", tinymce.models.HTMLField()),
            ],
            options={
                "verbose_name": "Voorwaarde",
                "verbose_name_plural": "Voorwaarden",
                "ordering": ["titel"],
            },
        ),
    ]
