# Generated by Django 4.2.23 on 2025-08-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("muziekschool", "0016_voorwaarde"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="voorwaarde",
            name="info",
        ),
        migrations.AddField(
            model_name="voorwaarde",
            name="regel1",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="voorwaarde",
            name="regel2",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="voorwaarde",
            name="regel3",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="voorwaarde",
            name="regel4",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name="voorwaarde",
            name="titel",
            field=models.CharField(max_length=64),
        ),
    ]
