# Generated by Django 4.2.7 on 2025-07-15 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BrandingAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("logo", models.ImageField(upload_to="branding/logos/")),
                (
                    "icon",
                    models.ImageField(
                        blank=True, null=True, upload_to="branding/icons/"
                    ),
                ),
                (
                    "font_file",
                    models.FileField(
                        blank=True, null=True, upload_to="branding/fonts/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DesignPattern",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("primary_color", models.CharField(default="#000000", max_length=7)),
                ("secondary_color", models.CharField(default="#FFFFFF", max_length=7)),
                ("accent_color", models.CharField(blank=True, max_length=7, null=True)),
                ("font_family", models.CharField(default="Arial", max_length=100)),
            ],
        ),
    ]
