# Generated by Django 4.2.7 on 2025-07-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branding", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="designpattern",
            name="name",
            field=models.CharField(default="schema", max_length=64),
        ),
    ]
