# Generated by Django 4.2.7 on 2025-06-19 16:04

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Instrument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("naam", models.CharField(max_length=128)),
                ("beschrijving", tinymce.models.HTMLField()),
                (
                    "image",
                    models.ImageField(default="default.jpg", upload_to="instrument"),
                ),
                ("link", models.URLField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["naam"],
            },
        ),
        migrations.CreateModel(
            name="LesType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("soort", models.CharField(max_length=128)),
                ("duur", models.PositiveSmallIntegerField(default=30)),
                ("aantal", models.PositiveSmallIntegerField(default=38)),
                ("beschrijving", models.CharField(max_length=128)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["soort", "duur"],
            },
        ),
        migrations.CreateModel(
            name="Locatie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("naam", models.CharField(max_length=128)),
                ("adres", models.CharField(max_length=128)),
                ("kaart", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["naam"],
            },
        ),
        migrations.CreateModel(
            name="LesTarief",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prijs_ex", models.DecimalField(decimal_places=2, max_digits=10)),
                ("prijs_inc", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="knack.lestype"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "lestarieven",
                "ordering": ["type__soort", "prijs_ex"],
            },
        ),
        migrations.CreateModel(
            name="Docent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("naam", models.CharField(max_length=128)),
                (
                    "image",
                    models.ImageField(default="default.jpg", upload_to="docenten"),
                ),
                ("bio", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "instrumenten",
                    models.ManyToManyField(blank=True, to="knack.instrument"),
                ),
            ],
            options={
                "ordering": ["naam"],
            },
        ),
    ]
