# Generated by Django 4.2.7 on 2025-07-27 00:03

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("knack", "0002_alter_docent_image_alter_instrument_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instrument",
            name="beschrijving",
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
