# Generated by Django 4.2.7 on 2025-07-27 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knack", "0003_alter_instrument_beschrijving"),
    ]

    operations = [
        migrations.AlterField(
            model_name="docent",
            name="image",
            field=models.ImageField(default="default.jpg", upload_to="docenten"),
        ),
        migrations.AlterField(
            model_name="instrument",
            name="image",
            field=models.ImageField(default="default.jpg", upload_to="instrument"),
        ),
        migrations.AlterField(
            model_name="instrument",
            name="naam",
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
