# Generated by Django 4.2.7 on 2025-07-27 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knack", "0004_alter_docent_image_alter_instrument_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lestype",
            name="prijs_ex",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="lestype",
            name="prijs_inc",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="lestype",
            name="beschrijving",
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
