# Generated by Django 4.2.7 on 2025-07-27 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knack", "0005_lestype_prijs_ex_lestype_prijs_inc_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lestype",
            name="naam",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name="lestype",
            name="soort",
            field=models.CharField(max_length=12),
        ),
    ]
