# Generated by Django 4.2.7 on 2025-07-29 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("knack", "0006_lestype_naam_alter_lestype_soort"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="docent",
            options={"ordering": ["naam"], "verbose_name_plural": "Docenten"},
        ),
        migrations.AlterModelOptions(
            name="instrument",
            options={"ordering": ["naam"], "verbose_name_plural": "Instrumenten"},
        ),
    ]
