# Generated by Django 4.2.23 on 2025-08-18 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knack", "0007_alter_docent_options_alter_instrument_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lestype",
            name="naam",
            field=models.CharField(blank=True, max_length=128, unique=True),
        ),
    ]
