# Generated by Django 4.2.23 on 2025-08-29 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knack", "0008_alter_lestype_naam"),
    ]

    operations = [
        migrations.AlterField(
            model_name="locatie",
            name="kaart",
            field=models.URLField(blank=True, max_length=256, null=True),
        ),
    ]
