# Generated by Django 4.2.23 on 2025-08-29 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knack", "0009_alter_locatie_kaart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="locatie",
            name="adres",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="locatie",
            name="naam",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
