# Generated by Django 4.2.7 on 2025-06-30 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="image",
            field=models.ImageField(default="default.png", upload_to="event"),
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(default="default.png", upload_to="agenda"),
        ),
    ]
