# Generated by Django 4.2.23 on 2025-08-12 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0002_alter_event_image_alter_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="image",
            field=models.ImageField(default="default.jpg", upload_to="event"),
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(default="default.jpg", upload_to="agenda"),
        ),
    ]
