# Generated by Django 4.2.7 on 2025-06-19 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("knack", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bericht",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("naam", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("bericht", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name_plural": "berichten",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Betalingsplichtige",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("initialen", models.CharField(max_length=10)),
                ("achternaam", models.CharField(max_length=100)),
                ("adres", models.CharField(max_length=100)),
                ("postcode", models.CharField(max_length=6)),
                ("iban", models.CharField(max_length=100)),
                ("plaats", models.CharField(max_length=100)),
                ("haarlempas", models.BooleanField(default=False)),
                ("akkoord", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "betalingsplichtigen",
                "ordering": ["achternaam", "initialen"],
            },
        ),
        migrations.CreateModel(
            name="Proefles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("naam", models.CharField(max_length=100)),
                ("telefoon", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "In behandeling"),
                            ("scheduled", "Ingepland"),
                            ("completed", "Voltooid"),
                            ("cancelled", "Geannuleerd"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="knack.instrument",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "proeflessen",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Inschrijving",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("voornaam", models.CharField(max_length=100)),
                ("achternaam", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("telefoon", models.CharField(max_length=20)),
                ("geboortedatum", models.DateField()),
                ("huren", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "In behandeling"),
                            ("approved", "Goedgekeurd"),
                            ("rejected", "Afgewezen"),
                            ("active", "Actief"),
                            ("inactive", "Inactief"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "betalingsplichtige",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inbox.betalingsplichtige",
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="knack.instrument",
                    ),
                ),
                (
                    "lestype",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="knack.lestype",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "inschrijvingen",
                "ordering": ["-created_at"],
            },
        ),
    ]
